const allCard1 = [
  { card: "AS", value: "12" },
  { card: "AH", value: "12" },
  { card: "AC", value: "12" },
  { card: "AD", value: "12" },
  { card: "2S", value: "13" },
  { card: "2H", value: "13" },
  { card: "2C", value: "13" },
  { card: "2D", value: "13" },
  { card: "3S", value: "1" },
  { card: "3H", value: "1" },
  { card: "3C", value: "1" },
  { card: "3D", value: "1" },
  { card: "4S", value: "2" },
  { card: "4H", value: "2" },
  { card: "4C", value: "2" },
  { card: "4D", value: "2" },
  { card: "5S", value: "3" },
  { card: "5H", value: "3" },
  { card: "5C", value: "3" },
  { card: "5D", value: "3" },
  { card: "6S", value: "4" },
  { card: "6H", value: "4" },
  { card: "6C", value: "4" },
  { card: "6D", value: "4" },
  { card: "7S", value: "5" },
  { card: "7H", value: "5" },
  { card: "7C", value: "5" },
  { card: "7D", value: "5" },
  { card: "8S", value: "6" },
  { card: "8H", value: "6" },
  { card: "8C", value: "6" },
  { card: "8D", value: "6" },
  { card: "9S", value: "7" },
  { card: "9H", value: "7" },
  { card: "9C", value: "7" },
  { card: "9D", value: "7" },
  { card: "0S", value: "8" },
  { card: "0H", value: "8" },
  { card: "0C", value: "8" },
  { card: "0D", value: "8" },
  { card: "JS", value: "9" },
  { card: "JH", value: "9" },
  { card: "JC", value: "9" },
  { card: "JD", value: "9" },
  { card: "QS", value: "10" },
  { card: "QH", value: "10" },
  { card: "QC", value: "10" },
  { card: "QD", value: "10" },
  { card: "KS", value: "11" },
  { card: "KH", value: "11" },
  { card: "KC", value: "11" },
  { card: "KD", value: "11" },
  { card: "X2", value: "14" },
  { card: "X1", value: "15" },
];
const allCard2 = {
  AS: "12",
  AH: "12",
  AC: "12",
  AD: "12",
  "2S": "13",
  "2H": "13",
  "2C": "13",
  "2D": "13",
  "3S": "1",
  "3H": "1",
  "3C": "1",
  "3D": "1",
  "4S": "2",
  "4H": "2",
  "4C": "2",
  "4D": "2",
  "5S": "3",
  "5H": "3",
  "5C": "3",
  "5D": "3",
  "6S": "4",
  "6H": "4",
  "6C": "4",
  "6D": "4",
  "7S": "5",
  "7H": "5",
  "7C": "5",
  "7D": "5",
  "8S": "6",
  "8H": "6",
  "8C": "6",
  "8D": "6",
  "9S": "7",
  "9H": "7",
  "9C": "7",
  "9D": "7",
  "0S": "8",
  "0H": "8",
  "0C": "8",
  "0D": "8",
  JS: "9",
  JH: "9",
  JC: "9",
  JD: "9",
  QS: "10",
  QH: "10",
  QC: "10",
  QD: "10",
  KS: "11",
  KH: "11",
  KC: "11",
  KD: "11",
  X2: "14",
  X1: "15",
};

export default {
  allCard1,
  allCard2,
};
